pack:
  metadata:
    title: "pixel.ai"
    description: "anything in → one pixel out"

  css:
    - ./web/style.css

  html:
    - ./web/body.html

  scripts:
    - https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js
    - https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/controls/TrackballControls.js
    - https://cdn.jsdelivr.net/npm/three@0.128.0/examples/js/libs/stats.min.js
    - ./web/viz.js
    - ./web/app.js

  wasm:
    app:
      binary: ./pkg_nomodules/pixel_ai_bg.wasm
      glue: ./pkg_nomodules/pixel_ai.js
      id: "bin-wasm-app"
      compression: "brotli"
